#!/bin/bash

cd ..
mkdir -p terrariaserver
cd terrariaserver
wget https://github.com/Pryaxis/TShock/releases/download/v5.1.3/TShock-5.1.3-for-Terraria-1.4.4.9-win-x64-Release.zip
unzip TShock-5.1.3-for-Terraria-1.4.4.9-win-x64-Release.zip

echo -e "Install Complete"
