#!/bin/bash
sudo apt update -qq

cd ..
mkdir -p terrariaserver
cd terrariaserver
wget https://github.com/NyxStudios/TShock/releases/download/v4.3.23/tshock_4.3.23.zip
unzip tshock_4.3.23.zip

echo -e "Install Complete"
