#!/bin/bash
sudo apt update -qq

cd ..
mkdir -p terrariaserver
cd terrariaserver
wget https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre12/TShock4.4.0_Pre12_Terraria1.4.0.5.zip
unzip TShock4.4.0_Pre12_Terraria1.4.0.5.zip

echo -e "Install Complete"
