#!/bin/bash
mkdir bin
chmod +x *
export MAIN_DIR=$PWD
echo "Which Server do you want to install?"
echo "Type [1] Terraria Server"
echo "Type [2] Test Server"

choiceForServer=1
read choiceForServer

# Installing

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
cd $MAIN_DIR/bin
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update
sudo apt-get install mono-complete
sudo apt-get install unzip zip

cd $MAIN_DIR
# If choice is 0 or null then run this command
if [[ -z $choiceForServer ]]; then

  echo "> Invaild Respond. Please try again."
  ./install

# If choice is 1 then run this command
elif [[ $choiceForServer == 1 ]]; then
	
	echo "> Running Tshock Installation..."
  ./installTerraria

# If choice is 1 then run this command
elif [[ $choiceForServer == 2 ]]; then
	
	echo "> This for test only. Please try again."
  ./install

else
	echo "> Invaild Respond. Please try again."
	./install
fi
echo ""

