#!/bin/bash

export THIS_DIR=$PWD

install_server () {
  choice=$1
  if [[ -z $choice ]]
  then	
    echo -e "\n> Installing Tshock..."
    cd ServersInstallScripts
    chmod +x *
    
    ./Tshock
    errorno=${?}
    if [ $errorno -eq 1 ]
    then
      cd $THIS_DIR
      install_server $choice
    fi


  # Tshock
  elif [[ $choice == 1 ]]
  then
    echo -e "\n> Installing Tshock..."
    cd ServersInstallScripts
    chmod +x *

    ./Tshock
    errorno=${?}
    if [ $errorno -eq 1 ]
    then
	    cd $THIS_DIR
      install_server $choice
    fi
    
    
 # Invaild Input
  else
    echo "Invaild Responds! Please try again"
    ./installTerraria
  fi
}

#Installing all the dependencise
sudo apt-get install unzip zip
sudo apt-get -y install screen

echo "export PATH=$PATH:/some/new/path" > ~/.profile
echo "> Dependencies Installtion Completed!"

#Downloading playit && Downloading Terraria Server
mkdir terrariaserver

echo ""
echo "-- Pick the following Server type: --"
echo "Type [1] Create Default Tshock Server"
echo "Type [2] Create Other Server"
choiceForServer=1
read choiceForServer

install_server $choiceForServer

# Backup install playit.gg in case if first one doesn't download
echo "> Installing Playit.gg..."
cd ..
#wget "https://playit.gg/downloads/playit-linux_64-0.4.2-rc1" -O playit 
#wget -q "https://playit.gg/downloads/playit-linux_64-0.4.6" -O playit
#wget -q "https://new.playit.gg/downloads/playit-0.7.0-beta" -O playit
#wget -q "https://playit.gg/downloads/playit-0.7.5-beta" -O playit
#wget -q "https://playit.gg/downloads/playit-0.8.1-beta" -O playit
wget -q "https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3" -O playit
chmod +x playit
echo "> Playit.gg Installation Completed!"
echo ""
echo "-- Do you want to start the server now? --"
echo "Type [1] for Yes"
echo "Type [2] for No"

StartServer=2
read StartServer

if [[ -z $StartServer ]]; then
echo "> By Default, you selected 'No'."
echo "> You can start the server by do ./startserver"

elif [[ $StartServer == 1 ]]; then
./startserver

elif [[ $StartServer == 2 ]]; then
echo "You picked 'No'."
echo "> You can start the server by do ./startserver"

else
echo "> By Default, you selected 'No'."
echo "> You can start the server by do ./startserver"
fi
