#!/bin/bash
export MAIN_DIR=$PWD
echo "> Starting the server up. Please wait..."                                                                                 
echo "> Installing Dependencise..."

sudo apt install -y -qq screen wget  

echo "> Dependencise Installed!"


# apparently ppl keep spamming startserver and end up having multiple screens of the same app
killall screen

screen -S server -d -m ./startTshockServer # Starting Java Server
screen -S playit -d -m ./startPlayIt # Starting Playit


cd $MAIN_DIR

echo "-- Your Server is now ONLINE! --"
echo
echo "Type [screen -ls] to check the Running Processes"
echo "Type [screen -r server] to enter the Server Console"
echo "Type [screen -r playit] to view your Server IP"
echo ""
echo "> To stop your server, type './stopserver' to stop"

echo -e '\nchecking if server has launched properly'
./.checkserver 2> crash.log
